// <auto-generated />
using System;
using HexaEmployee.EfInfraData.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HexaEmployee.EfInfraData.Migrations
{
    [DbContext(typeof(HexaEmployeeDbContext))]
    [Migration("20220227153638_CreateSalaryHistoryTable")]
    partial class CreateSalaryHistoryTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("HexaEmployee.EfInfraData.Models.EmployeeTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("NAME");

                    b.HasKey("Id");

                    b.ToTable("EMPLOYEE");
                });

            modelBuilder.Entity("HexaEmployee.EfInfraData.Models.SalaryHistoryTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<decimal>("Salary")
                        .HasColumnType("MONEY")
                        .HasColumnName("SALARY");

                    b.Property<DateTimeOffset>("SalaryRaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("RAISED_AT");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EMPLOYEE_SALARY_HISTORY");
                });

            modelBuilder.Entity("HexaEmployee.EfInfraData.Models.SalaryHistoryTable", b =>
                {
                    b.HasOne("HexaEmployee.EfInfraData.Models.EmployeeTable", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
