// <auto-generated />
using System;
using HexaEmployee.EfInfraData.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace HexaEmployee.EfInfraData.Migrations
{
    [DbContext(typeof(HexaEmployeeDbContext))]
    [Migration("20220226155746_CreateEmployeeTable")]
    partial class CreateEmployeeTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("HexaEmployee.Domain.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTimeOffset>("LastSalaryRaise")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("SALARY_RAISE_DATE");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("NAME");

                    b.Property<decimal>("Salary")
                        .HasColumnType("MONEY")
                        .HasColumnName("SALARY");

                    b.HasKey("Id");

                    b.ToTable("EMPLOYEE");
                });
#pragma warning restore 612, 618
        }
    }
}
